services:
  db:
    image: postgres:16.0-alpine3.17
    container_name: psgr
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - planetarium_db:/var/lib/postgresql/data

  planetarium:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  planetarium_db:
